# Generated by Django 5.1.7 on 2026-01-06 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restroom_id', models.CharField(help_text='Unique Identifier for the restroom', max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField(help_text='Latitude for map location')),
                ('longitude', models.FloatField(help_text='Longitude for map location')),
                ('status', models.CharField(choices=[('Operational', 'Operational'), ('Maintenance', 'Maintenance'), ('Cleaning', 'Cleaning'), ('Inactive', 'Inactive')], default='Operational', max_length=20)),
                ('capacity', models.IntegerField(help_text='Maximum capacity of the restroom')),
                ('last_cleaned', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restrooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
