# Generated by Django 5.1.7 on 2026-01-06 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(help_text='Unique Identifier for the sensor', max_length=50, unique=True)),
                ('sensor_type', models.CharField(help_text='Type of sensor (e.g. Ammonia, Temp)', max_length=50)),
                ('threshold_min', models.FloatField(blank=True, help_text='Minimum threshold value', null=True)),
                ('threshold_max', models.FloatField(blank=True, help_text='Maximum threshold value', null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Calibration', 'Calibration')], default='Active', max_length=20)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('restroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='landing.restroom')),
            ],
        ),
    ]
