# Generated by Django 5.1.7 on 2026-01-06 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_sensorreading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='restroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensors', to='landing.restroom'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type',
            field=models.CharField(help_text='Type of sensor (e.g. Ammonia, Smoke,Footfall)', max_length=50),
        ),
    ]
