# Generated by Django 5.1.7 on 2026-01-06 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_alter_sensor_restroom_alter_sensor_sensor_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorreading',
            name='status',
        ),
    ]
