# Generated by Django 5.1.7 on 2026-01-07 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_remove_sensorreading_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
                ('role', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nfc_tag', models.CharField(help_text='NFC Tag ID', max_length=100, unique=True)),
                ('restroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='landing.restroom')),
            ],
        ),
    ]
