# Generated by Django 5.1.7 on 2026-01-07 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(help_text='Type of cleaning activity (e.g., Deep Clean)', max_length=100)),
                ('start_time', models.DateTimeField(help_text='Scheduled start time')),
                ('end_time', models.DateTimeField(blank=True, help_text='Actual completion time', null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Complete', 'Complete')], default='Pending', max_length=20)),
                ('restroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_activities', to='landing.restroom')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaning_activities', to='landing.staff')),
            ],
        ),
    ]
